import Foundation
import Testing
@testable import LowkeyCore

/// Differential tests: TextPipeline must reproduce the CLI's bash/Perl cleanup
/// byte for byte. Expected outputs live in tests/fixtures/cleanup/expected.json,
/// generated by tests/gen-cleanup-fixtures.sh from the real bash functions.
/// Strings are compared as UTF-8 bytes, never with String == (which treats
/// canonically equivalent strings as equal).
struct CleanupParityTests {
  static let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()  // LowkeyCoreTests
    .deletingLastPathComponent()  // Tests
    .deletingLastPathComponent()  // tmux-whisperd
    .deletingLastPathComponent()
  static let fixtures = repoRoot.appendingPathComponent("tests/fixtures/cleanup")

  struct StageCase: Decodable {
    let id: String
    let fn: String
    let args: [String]
    let input: String
    let output: String
  }

  /// `current_mode`: absent keeps the fixture's file, a string replaces it,
  /// `false` deletes it.
  enum CurrentMode: Decodable {
    case write(String)
    case delete

    init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let text = try? container.decode(String.self) {
        self = .write(text)
      } else {
        self = .delete
      }
    }
  }

  struct PipelineCase: Decodable {
    let id: String
    let config: String
    let app: String
    let input: String
    let currentMode: CurrentMode?
    let settings: CleanupSettings
    let status: String
    let rawText: String
    let text: String
    let mode: String?

    enum CodingKeys: String, CodingKey {
      case id, config, app, input, settings, status, text, mode
      case currentMode = "current_mode"
      case rawText = "raw_text"
    }
  }

  struct Expected: Decodable {
    let stage: [StageCase]
    let pipeline: [PipelineCase]
  }

  /// JSONDecoder, not JSONSerialization: the latter drops U+FEFF in strings.
  static func loadExpected() throws -> Expected {
    let data = try Data(contentsOf: fixtures.appendingPathComponent("expected.json"))
    return try JSONDecoder().decode(Expected.self, from: data)
  }

  static func configPath(_ name: String) -> String {
    name == "repo"
      ? repoRoot.appendingPathComponent("config").path
      : fixtures.appendingPathComponent("configs/\(name)").path
  }

  /// Records a byte mismatch with enough context to debug it.
  static func check(_ id: String, _ what: String, actual: String, expected: String, failures: inout Int) {
    let a = Array(actual.utf8)
    let e = Array(expected.utf8)
    guard a != e else { return }
    failures += 1
    guard failures <= 25 else { return }
    let firstDiff = (0..<min(a.count, e.count)).first { a[$0] != e[$0] } ?? min(a.count, e.count)
    Issue.record("""
      \(id) \(what) differs at byte \(firstDiff)
        expected: \(expected.debugDescription)
        actual:   \(actual.debugDescription)
      """)
  }

  @Test func stageFunctionsMatchBash() throws {
    let cases = try Self.loadExpected().stage
    #expect(cases.count > 500)
    var failures = 0
    for item in cases {
      let arg0 = item.args.first ?? ""
      let arg1 = item.args.count > 1 ? item.args[1] : ""
      let actual: String
      switch item.fn {
      case "sanitize": actual = TextCleanup.sanitizeArtifacts(item.input)
      case "fillers": actual = TextCleanup.cleanFillers(item.input)
      case "repeats":
        // dictate_lib_clean_repeats defaults an empty level to 1.
        actual = TextCleanup.cleanRepeats(item.input, level: PerlText.perlInt(arg0.isEmpty ? "1" : arg0))
      case "british": actual = TextCleanup.normalizeBritishSpelling(item.input, enabled: arg0)
      case "paragraphs": actual = TextCleanup.autoParagraphs(item.input, mode: arg0, minWords: arg1)
      case "vocab": actual = VocabCorrector(configDir: Self.configPath(arg1), mode: arg0).apply(item.input)
      default:
        Issue.record("\(item.id): unknown stage \(item.fn)")
        continue
      }
      Self.check(item.id, item.fn, actual: actual, expected: item.output, failures: &failures)
    }
    #expect(failures == 0, "\(failures) stage cases differ from bash")
  }

  @Test func pipelineMatchesInlineCleanup() throws {
    let cases = try Self.loadExpected().pipeline
    #expect(cases.count > 100)
    let fm = FileManager.default
    let scratch = fm.temporaryDirectory.appendingPathComponent("lowkey-cleanup-parity-\(UUID().uuidString)")
    try fm.createDirectory(at: scratch, withIntermediateDirectories: true)
    defer { try? fm.removeItem(at: scratch) }
    var failures = 0
    var sawPostprocess = false
    var sawLocale = false
    for (index, item) in cases.enumerated() {
      let configDir = scratch.appendingPathComponent("\(index)").path
      try fm.copyItem(atPath: Self.configPath(item.config), toPath: configDir)
      let modeFile = configDir + "/current-mode"
      switch item.currentMode {
      case .write(let text): try Data(text.utf8).write(to: URL(fileURLWithPath: modeFile))
      case .delete: try? fm.removeItem(atPath: modeFile)
      case nil: break
      }

      var settings = item.settings
      #expect(settings.configDir == "@config")
      settings.configDir = configDir
      let outcome = TextPipeline(settings: settings).process(transcript: item.input, app: item.app)

      if settings.requiresCLI {
        if settings.postprocess { sawPostprocess = true } else { sawLocale = true }
        #expect(outcome == .needsCLI, "\(item.id): must fall back to the CLI")
        continue
      }
      switch (item.status, outcome) {
      case ("no_speech", .noSpeech):
        break
      case ("ok", .text(let raw, let text, let mode)):
        Self.check(item.id, "raw_text", actual: raw, expected: item.rawText, failures: &failures)
        Self.check(item.id, "text", actual: text, expected: item.text, failures: &failures)
        Self.check(item.id, "mode", actual: mode, expected: item.mode ?? "", failures: &failures)
      default:
        failures += 1
        Issue.record("\(item.id): bash status \(item.status) but Swift gave \(outcome)")
      }
    }
    #expect(sawPostprocess, "the corpus should cover the LLM fallback")
    #expect(sawLocale, "the corpus should cover the non-C locale fallback")
    #expect(failures == 0, "\(failures) pipeline cases differ from bash")
  }

  @Test func nonCLocaleFallsBackToTheCLI() {
    #expect(!CleanupSettings(configDir: "/c").requiresCLI)
    #expect(!CleanupSettings(configDir: "/c", localeCtype: "POSIX", localeCollate: nil).requiresCLI)
    let utf8 = CleanupSettings(configDir: "/c", localeCtype: "en_US.UTF-8", localeCollate: "en_US.UTF-8")
    #expect(utf8.requiresCLI)
    #expect(TextPipeline(settings: utf8).process(transcript: "hello", app: "Ghostty") == .needsCLI)
  }

  @Test func appConfigCleanupSectionDecodes() throws {
    let json = """
      {"config_dir": "/tmp/x", "clean": "1", "repeats_level": "2", "vocab_clean": "1",
       "british_spelling": "0", "code_paragraph_min_words": "70", "long_paragraph_min_words": "55",
       "force_mode": null, "postprocess": false}
      """
    let settings = try JSONDecoder().decode(CleanupSettings.self, from: Data(json.utf8))
    #expect(settings == CleanupSettings(
      configDir: "/tmp/x", clean: "1", repeatsLevel: "2", britishSpelling: "0"))
  }
}

struct ShadowCompareTests {
  @Test func agreesOnIdenticalResults() {
    let native = CleanupOutcome.text(raw: "open ai", text: "OpenAI", mode: "code")
    #expect(ShadowCompare.mismatch(native: native, cliStatus: "ok", cliRawText: "open ai", cliText: "OpenAI", cliMode: "code") == nil)
    #expect(ShadowCompare.mismatch(native: .noSpeech, cliStatus: "no_speech", cliRawText: "", cliText: "", cliMode: nil) == nil)
    #expect(ShadowCompare.mismatch(native: .needsCLI, cliStatus: "failed", cliRawText: "", cliText: "", cliMode: nil) == nil)
  }

  @Test func reportsCanonicallyEquivalentButDifferentBytes() {
    let native = CleanupOutcome.text(raw: "cafe\u{301}", text: "cafe\u{301}", mode: "base")
    let report = ShadowCompare.mismatch(native: native, cliStatus: "ok", cliRawText: "caf\u{E9}", cliText: "caf\u{E9}", cliMode: "base")
    #expect(report?.contains("raw native=") == true)
    #expect(report?.contains("text native=") == true)
    #expect(report?.contains("mode") == false)
    let modeReport = ShadowCompare.mismatch(
      native: .text(raw: "x", text: "x", mode: "cafe\u{301}"), cliStatus: "ok", cliRawText: "x", cliText: "x",
      cliMode: "caf\u{E9}")
    #expect(modeReport?.contains("mode native=") == true)
  }

  @Test func reportsStatusAndModeDifferences() {
    let native = CleanupOutcome.text(raw: "hi", text: "hi", mode: "code")
    #expect(ShadowCompare.mismatch(native: native, cliStatus: "no_speech", cliRawText: "", cliText: "", cliMode: nil)?
      .contains("cli=no_speech") == true)
    #expect(ShadowCompare.mismatch(native: native, cliStatus: "ok", cliRawText: "hi", cliText: "hi", cliMode: "base")?
      .contains("mode native=") == true)
  }
}

struct PerlTextTests {
  @Test func perlIntFollowsPerlNumification() {
    #expect(PerlText.perlInt("2") == 2)
    #expect(PerlText.perlInt(" 2") == 2)
    #expect(PerlText.perlInt("2abc") == 2)
    #expect(PerlText.perlInt("1e1") == 10)
    #expect(PerlText.perlInt("1.9") == 1)
    #expect(PerlText.perlInt("2.") == 2)
    #expect(PerlText.perlInt(".5") == 0)
    #expect(PerlText.perlInt("-1") == -1)
    #expect(PerlText.perlInt("abc") == 0)
    #expect(PerlText.perlInt("") == 0)
    #expect(PerlText.perlInt("0x10") == 0)
    #expect(PerlText.perlInt("Inf") == .infinity)
    #expect(PerlText.perlInt("nan").isNaN)
  }

  @Test func eachLineKeepsTerminators() {
    var lines: [String] = []
    _ = PerlText.eachLine("a\r\nb\n\nc") { lines.append($0); return $0 }
    #expect(lines == ["a\r\n", "b\n", "\n", "c"])
  }

  @Test func bashCaptureDropsTrailingNewlinesOnly() {
    #expect(PerlText.bashCapture("a\n\n") == "a")
    #expect(PerlText.bashCapture("a\r\n") == "a\r")
    #expect(PerlText.bashCapture("\na\0b ") == "\nab ")
  }

  @Test func byteModeRoundTripsUnicode() {
    let text = "café \u{212A} 日本 😀 e\u{301}"
    #expect(Array(PerlText.byteMode(text) { $0 }.utf8) == Array(text.utf8))
  }
}
